Repository clairBuoyant/server, pull requests merged in 2022-06, with the labels that each got.

#18 devops: add GitHub action workflow for PRs
  .github/workflows/.gitkeep
  .github/workflows/fastapi-server.yml
  server/core/config.py
  server/schemas/buoy.py
  server/schemas/coastline.py
  server/seed_initial_data.py
  server/services/buoy/seed_buoys.py
  server/services/coastline/seed_coastline.py
Labels: devOps

#19 tests: improve coverage to 82%
  .dockerignore
  .github/workflows/fastapi-server.yml
  .gitignore
  .vscode/launch.json
  Dockerfile
  docs/README.md
  env-template
  migrations/env.py
  poetry.lock
  pyproject.toml
  server/api/dependencies.py
  server/api/v1/endpoints/coastlines.py
  server/core/config.py
  server/core/constants.py
  server/crud/crud_coastline.py
  server/db/database.py
  server/db/init_db.py
  server/db/session.py
  server/main.py
  server/seed_initial_data.py
  tests/api/test_coastlines.py
  tests/conftest.py
Labels: chore, enhancement, dependencies

#23 feat: support python 3.10 and greater
  .github/workflows/fastapi-server.yml
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: devOps, dependencies

#24 Chore/8 refactor crud
  .github/workflows/fastapi-server.yml
  server/api/v1/api.py
  server/api/v1/endpoints/buoys.py
  server/api/v1/endpoints/coastlines.py
  server/crud/base.py
  server/crud/crud_buoy.py
  server/crud/crud_coastline.py
  server/db/database.py
  server/main.py
  server/models/buoy.py
  server/models/coastline.py
  tests/api/test_coastlines.py
Labels: chore, tech-debt
